### ISSUE TITLE
im unable to change the server and sign in option is not working 

### ISSUE THREAD

**Issue by gusfing** [geekyAnkush/Ayame#1]
only  one server is showing and signing in option is not working and add watch togather option 
and nice working website is amazing

**Comment by avalynndev** [comment]
Imagine you asking for a Sign In option, when the developer hasn't added a function for the Button !!

**Comment by geekyAnkush** [comment]
Yeah the site is still work in progress and those two features are yet to be implemented

**Comment by gusfing** [comment]
> Yeah the site is still work in progress and those two features are yet to be implemented

Ohkk
